# Generated by Django 5.0.6 on 2024-05-30 03:36

import LifeBetterApp.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracionExterna',
            fields=[
                ('rut_admin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_admin', models.CharField(max_length=50)),
                ('fecha_contrato_admin', models.DateField()),
                ('correo_admin', models.EmailField(blank=True, max_length=50, null=True)),
                ('fono_contacto_admin', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('run_empleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dvrun_empleado', models.CharField(max_length=1, validators=[LifeBetterApp.models.validar_dv])),
                ('pnombre_empleado', models.CharField(max_length=50)),
                ('snombre_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('appaterno_empleado', models.CharField(max_length=50)),
                ('apmaterno_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento_empleado', models.DateField()),
                ('fecha_contrato_empleado', models.DateField()),
                ('correo_empleado', models.EmailField(blank=True, max_length=50, null=True)),
                ('fono_empleado', models.CharField(max_length=15)),
                ('tipo_empleado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EspacioComun',
            fields=[
                ('id_ec', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_ec', models.CharField(max_length=60)),
                ('descripcion_ec', models.CharField(max_length=60)),
                ('capacidad_ec', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('run_residente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dvrun', models.CharField(max_length=1, validators=[LifeBetterApp.models.validar_dv])),
                ('pnombre_residente', models.CharField(max_length=50)),
                ('snombre_residente', models.CharField(blank=True, max_length=50, null=True)),
                ('appaterno_residente', models.CharField(max_length=50)),
                ('apmaterno_residente', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento_residente', models.DateField()),
                ('fecha_contrato_residente', models.DateField()),
                ('correo_residente', models.EmailField(blank=True, max_length=50, null=True)),
                ('fono_residente', models.CharField(max_length=15)),
                ('tipo_residente', models.IntegerField()),
                ('comite', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('rut_visitante', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[LifeBetterApp.models.validar_rut])),
                ('dv_visitante', models.CharField(max_length=1, validators=[LifeBetterApp.models.validar_dv])),
                ('nombres_visitante', models.CharField(max_length=80)),
                ('apellido_visitante', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=60)),
                ('contenido', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('run_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_asunto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=60)),
                ('contenido_asunto', models.CharField(max_length=60)),
                ('fecha_hora_asunto', models.DateTimeField()),
                ('run_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='AdminEmpleadoContratada',
            fields=[
                ('id_admin_empleado_contratada', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rut_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.administracionexterna')),
                ('run_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado_reservacion', models.CharField(max_length=20)),
                ('inicio_fecha_hora_reservacion', models.DateTimeField()),
                ('fin_fecha_hora_reservacion', models.DateTimeField()),
                ('id_ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.espaciocomun')),
                ('run_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.residente')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion_multa', models.CharField(max_length=60)),
                ('monto_multa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_hora_multa', models.DateTimeField()),
                ('run_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.residente')),
            ],
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id_encomienda', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado_encomienda', models.CharField(max_length=20)),
                ('fecha_hora_encomienda', models.DateTimeField()),
                ('run_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.empleado')),
                ('run_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.residente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVisitanteDepto',
            fields=[
                ('id_visitante_depto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('run_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.residente')),
                ('run_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.visitante')),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id_estacionamiento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo_auto', models.IntegerField()),
                ('patente', models.CharField(max_length=6)),
                ('run_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.empleado')),
                ('run_residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.residente')),
                ('run_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.visitante')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('adminedificio', 'Administrador'), ('conserje', 'Conserje'), ('residente', 'Residente')], default='conserje', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
