# Generated by Django 5.0.6 on 2024-06-19 05:31

import LifeBetterApp.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracionExterna',
            fields=[
                ('rut_admin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_admin', models.CharField(max_length=50)),
                ('fecha_contrato_admin', models.DateField()),
                ('correo_admin', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('fono_contacto_admin', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Administración Externa',
                'verbose_name_plural': 'Administraciones Externas',
                'db_table': 'administracion_externa',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depto', models.AutoField(primary_key=True, serialize=False)),
                ('numero_depto', models.IntegerField()),
                ('piso', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('run_empleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dvrun_empleado', models.CharField(max_length=1, validators=[LifeBetterApp.models.validar_dv])),
                ('pnombre_empleado', models.CharField(max_length=50)),
                ('snombre_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('appaterno_empleado', models.CharField(max_length=50)),
                ('apmaterno_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento_empleado', models.DateField()),
                ('fecha_contrato_empleado', models.DateField()),
                ('correo_empleado', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('fono_empleado', models.CharField(max_length=15)),
                ('tipo_empleado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='EspacioComun',
            fields=[
                ('id_ec', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ec', models.CharField(max_length=60)),
                ('descripcion_ec', models.CharField(max_length=60)),
                ('capacidad_ec', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Espacio Común',
                'verbose_name_plural': 'Espacios Comunes',
                'db_table': 'espacio_comun',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=60)),
                ('contenido', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('run_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='LifeBetterApp.empleado')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_asunto', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=60)),
                ('contenido_asunto', models.CharField(max_length=60)),
                ('fecha_hora_asunto', models.DateTimeField()),
                ('run_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='LifeBetterApp.empleado')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'db_table': 'anuncio',
            },
        ),
        migrations.CreateModel(
            name='AdminEmpleadoContratada',
            fields=[
                ('id_admin_empleado_contratada', models.AutoField(primary_key=True, serialize=False)),
                ('rut_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='LifeBetterApp.administracionexterna')),
                ('run_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='LifeBetterApp.empleado')),
            ],
            options={
                'verbose_name': 'Admin Empleado Contratada',
                'verbose_name_plural': 'Admin Empleados Contratadas',
                'db_table': 'admin_empleado_contratada',
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('rut_residente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dvrun', models.CharField(max_length=1, validators=[LifeBetterApp.models.validar_dv])),
                ('pnombre_residente', models.CharField(max_length=50)),
                ('snombre_residente', models.CharField(blank=True, max_length=50, null=True)),
                ('appaterno_residente', models.CharField(max_length=50)),
                ('apmaterno_residente', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento_residente', models.DateField()),
                ('fecha_contrato_residente', models.DateField()),
                ('correo_residente', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('fono_residente', models.CharField(max_length=15)),
                ('tipo_residente', models.IntegerField()),
                ('comite', models.BooleanField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.departamento')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'db_table': 'residente',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado_reservacion', models.CharField(max_length=20)),
                ('inicio_fecha_hora_reservacion', models.DateTimeField()),
                ('fin_fecha_hora_reservacion', models.DateTimeField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.departamento')),
                ('id_ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='LifeBetterApp.espaciocomun')),
                ('run_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='LifeBetterApp.residente')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'db_table': 'reservacion',
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id_reclamo', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=60)),
                ('contenido_reclamo', models.CharField(max_length=200)),
                ('fecha_hora_reclamo', models.DateTimeField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.departamento')),
                ('run_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='LifeBetterApp.residente')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'db_table': 'reclamo',
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_multa', models.CharField(max_length=60)),
                ('monto_multa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_hora_multa', models.DateTimeField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.departamento')),
                ('run_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='LifeBetterApp.residente')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'db_table': 'multa',
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id_encomienda', models.AutoField(primary_key=True, serialize=False)),
                ('estado_encomienda', models.CharField(max_length=20)),
                ('fecha_hora_encomienda', models.DateTimeField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.departamento')),
                ('run_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomiendas', to='LifeBetterApp.empleado')),
                ('run_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomiendas', to='LifeBetterApp.residente')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'db_table': 'encomienda',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('contenido_respuesta', models.CharField(max_length=200)),
                ('fecha_hora_respuesta', models.DateTimeField()),
                ('id_reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='LifeBetterApp.reclamo')),
                ('run_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='LifeBetterApp.empleado')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut_visitante', models.CharField(max_length=8, validators=[LifeBetterApp.models.validar_rut])),
                ('dv_visitante', models.CharField(max_length=1, validators=[LifeBetterApp.models.validar_dv])),
                ('nombres_visitante', models.CharField(max_length=80)),
                ('apellido_visitante', models.CharField(max_length=80)),
                ('estacionamiento', models.BooleanField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.departamento')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
            },
        ),
        migrations.CreateModel(
            name='RegistroVisitanteDepto',
            fields=[
                ('id_visitante_depto', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.departamento')),
                ('rut_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='LifeBetterApp.residente')),
                ('rut_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='LifeBetterApp.visitante')),
            ],
            options={
                'verbose_name': 'Registro Visitante Depto',
                'verbose_name_plural': 'Registros Visitante Depto',
                'db_table': 'registro_visitante_depto',
            },
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id_estacionamiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_auto', models.IntegerField()),
                ('patente', models.CharField(max_length=6)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.departamento')),
                ('run_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estacionamientos', to='LifeBetterApp.empleado')),
                ('run_residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estacionamientos', to='LifeBetterApp.residente')),
                ('run_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estacionamientos', to='LifeBetterApp.visitante')),
            ],
            options={
                'verbose_name': 'Estacionamiento',
                'verbose_name_plural': 'Estacionamientos',
                'db_table': 'estacionamiento',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('adminedificio', 'Administrador'), ('conserje', 'Conserje'), ('residente', 'Residente')], default='adminedificio', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GastosComunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
