# Generated by Django 4.2.1 on 2024-06-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrovisitantedepto',
            old_name='run_residente',
            new_name='rut_residente',
        ),
        migrations.RenameField(
            model_name='registrovisitantedepto',
            old_name='run_visitante',
            new_name='rut_visitante',
        ),
        migrations.RenameField(
            model_name='residente',
            old_name='run_residente',
            new_name='rut_residente',
        ),
    ]
