# Generated by Django 5.0.6 on 2024-06-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovisitantedepto',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='residente',
            name='tipo_residente',
            field=models.CharField(choices=[('dueño', 'Dueño'), ('arrendatario', 'Arrendatario')], max_length=20),
        ),
    ]
