# Generated by Django 5.0.6 on 2024-06-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='estado_reservacion',
        ),
        migrations.AddField(
            model_name='espaciocomun',
            name='estado_ec',
            field=models.CharField(default='disponible', max_length=20),
            preserve_default=False,
        ),
    ]
