# Generated by Django 5.0.6 on 2024-07-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0002_alter_user_options_rename_amount_gastoscomunes_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoscomunes',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Enero', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='espaciocomun',
            name='estado_ec',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('en_mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='gastoscomunes',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('adminedificio', 'Administrador'), ('conserje', 'Conserje'), ('residente', 'Residente')], default='adminedificio', max_length=13),
        ),
    ]
