# Generated by Django 5.0.6 on 2024-06-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0002_remove_empleado_tipo_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='gastoscomunes',
            old_name='amount',
            new_name='monto',
        ),
        migrations.AddField(
            model_name='gastoscomunes',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_comunes', to='LifeBetterApp.departamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('adminedificio', 'Administrador'), ('conserje', 'Conserje'), ('residente', 'Residente')], default='residente', max_length=13),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.ForeignKey(blank=True, limit_choices_to={'role': 'adminedificio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada')], default='disponible', max_length=20)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.edificio')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LifeBetterApp.edificio'),
        ),
        migrations.CreateModel(
            name='LocalComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], default='disponible', max_length=20)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeBetterApp.edificio')),
            ],
        ),
    ]
