# Generated by Django 5.0.6 on 2024-06-19 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0002_remove_registrovisitantedepto_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='estacionamiento',
        ),
        migrations.AddField(
            model_name='registrovisitantedepto',
            name='fecha_hora_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registrovisitantedepto',
            name='fecha_hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='patente',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
