# Generated by Django 5.0.6 on 2024-07-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0003_gastoscomunes_mes_alter_espaciocomun_estado_ec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='descripcion_encomienda',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='nombre_encomienda',
            field=models.CharField(default='Nombre', max_length=40),
        ),
    ]
