# Generated by Django 5.0.6 on 2024-07-05 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0004_encomienda_descripcion_encomienda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastoscomunes',
            name='usuario',
        ),
        migrations.AddField(
            model_name='residente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
