# Generated by Django 5.0.6 on 2024-06-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0002_remove_reservacion_estado_reservacion_and_more'),
        ('LifeBetterApp', '0004_remove_registrovisitantedepto_rut_residente_and_more'),
    ]

    operations = [
    ]
