# Generated by Django 5.0.6 on 2024-06-19 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0004_remove_registrovisitantedepto_rut_residente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='run_empleado',
            new_name='empleado',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo_empleado',
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='fecha_hora_encomienda',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
