# Generated by Django 5.0.6 on 2024-07-05 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0005_remove_gastoscomunes_usuario_residente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoscomunes',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_comunes', to='LifeBetterApp.departamento'),
        ),
    ]
