# Generated by Django 5.0.6 on 2024-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0005_merge_20240619_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciocomun',
            name='estado_ec',
            field=models.CharField(default='disponible', max_length=20),
        ),
    ]
