# Generated by Django 5.0.6 on 2024-06-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0005_rename_run_empleado_bitacora_empleado_and_more'),
        ('LifeBetterApp', '0006_alter_espaciocomun_estado_ec'),
    ]

    operations = [
    ]
