# Generated by Django 5.0.6 on 2024-07-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0006_alter_gastoscomunes_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_empleado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
