# Generated by Django 5.0.6 on 2024-07-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0006_alter_gastoscomunes_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apmaterno_empleado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='appaterno_empleado',
            field=models.CharField(default='Alejandria', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='pnombre_empleado',
            field=models.CharField(default='Alejandro', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='snombre_empleado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='appaterno_residente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residente',
            name='pnombre_residente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
