# Generated by Django 5.0.6 on 2024-07-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifeBetterApp', '0007_alter_empleado_sueldo_empleado'),
        ('LifeBetterApp', '0007_empleado_apmaterno_empleado_and_more'),
    ]

    operations = [
    ]
